defaults:
  runner: codex
  service: acquiring
  tags:
    - go
    - exchange_buy

available:
  target_branch:
    - u1
    - u1-1
    - u1-4
  namespace:
    - acquiring-u1
    - acquiring-u1-1
    - acquiring-u1-4
